# surfrad database interface

This database contains information about things that do not change all that frequently:

- instrument deployment
- instrument inventory

QC related databases, which change quit frequently,0 are disconnected to tis database as long as we are not having a central server that prevents simultanius writing.

mention to handle (store, performe operations, and return) data in xarry objects (Dataset, DataArray). Only use pandas if operation or equivalent perfomrance is not available in xarry objects. Use numpy arrays only if pandas ojects do not meet the requirements.

In [29]:
import sqlite3

In [30]:
import surfradpy.database as srfdb

In [31]:
reload(srfdb)

In [32]:
p2db = 'surfrad_database.db'
db = srfdb.SurfradDatabase(p2db)

In [33]:
df = db.execute_query('SELECT * FROM sites WHERE network = "surfrad"')
df

,index,site_id,abb,name,elevation,latitude,longitude,network
0,0,1,tbl,Table Mountain,1689.0,40.124980,-105.236800,surfrad
1,1,2,bnd,Bondville,230.0,40.051920,-88.373090,surfrad
2,1,2,bon,Bondville,230.0,40.051920,-88.373090,surfrad
3,3,3,sxf,Sioux Falls,473.0,43.734030,-96.623280,surfrad
4,4,4,dra,Desert Rock,1007.0,36.623730,-116.019470,surfrad
5,5,5,fpk,Fort Peck,634.0,48.307830,-105.101700,surfrad
6,5,5,fpe,Fort Peck,634.0,48.307830,-105.101700,surfrad
7,7,6,gwn,Goodwin Creek,98.0,34.254700,-89.872900,surfrad
8,8,7,psu,Penn. State Univ.,376.0,40.720120,-77.930850,surfrad
9,9,8,inl,Idaho Falls,1496.5,43.594919,-112.928561,surfrad

In [34]:
df.rename({'latitude'}

_IncompleteInputError: incomplete input (3673968393.py, line 1)

In [ ]:
import atmPy.general.measurement_site as atmms

In [ ]:
nw = atmms.Network([l.to_dict() for i,l in df.iterrows()])

In [ ]:
nw.stations.Table_Mountain.lat

In [ ]:
atmms.Network()

In [ ]:
db.snapshot().keys()

In [ ]:
db.snapshot()['tables']

In [ ]:
out = db.dump_table('deployments')

In [ ]:
out.where(out.Location == 'inl').dropna()

In [ ]:
out[out.where(out.Location == 'inl')]

In [ ]:
db.dump_table('sites')

In [ ]:
db.dump_table('instruments_mfrsr')

## some useful commands

In [ ]:
# delete table
db.execute_query('DROP TABLE IF EXISTS [what to delet];')

# Tabels

## Sites

In [31]:
db.dump_table('sites')

,index,site_id,abb,name,elevation,latitude,longitude,network
0,0,1,tbl,Table Mountain,1689.0,40.124980,-105.236800,surfrad
1,1,2,bnd,Bondville,230.0,40.051920,-88.373090,surfrad
2,1,2,bon,Bondville,230.0,40.051920,-88.373090,surfrad
3,3,3,sxf,Sioux Falls,473.0,43.734030,-96.623280,surfrad
4,4,4,dra,Desert Rock,1007.0,36.623730,-116.019470,surfrad
5,5,5,fpk,Fort Peck,634.0,48.307830,-105.101700,surfrad
6,5,5,fpe,Fort Peck,634.0,48.307830,-105.101700,surfrad
7,7,6,gwn,Goodwin Creek,98.0,34.254700,-89.872900,surfrad
8,8,7,psu,Penn. State Univ.,376.0,40.720120,-77.930850,surfrad
9,9,8,inl,Idaho Falls,1496.5,43.594919,-112.928561,surfrad
10,10,9,ABC,Example Site,1520.5,39.739200,-104.990300,MyNetwork

### add a site

In [1]:
import surfradpy.database as srfdb

In [29]:
reload(srfdb)

In [30]:
p2db = 'surfrad_database.db'
db = srfdb.SurfradDatabase(p2db)

In [23]:
idx = db.execute_query('SELECT COALESCE(MAX("index"), 0) + 1 FROM sites')
idx = int(idx.iloc[0,0])

In [24]:
site_id = db.execute_query('SELECT COALESCE(MAX("site_id"), 0) + 1 FROM sites')
site_id = int(site_id.iloc[0,0])

In [ ]:
site = {
    "index": idx,
    "site_id": site_id,
    "abb": "ABC",
    "name": "Example Site",
    "elevation": 1520.5,
    "latitude": 39.7392,
    "longitude": -104.9903,
    "network": "MyNetwork",
}
site

db.execute_query(
    """
    INSERT INTO sites ("index", site_id, abb, name, elevation, latitude, longitude, network)
    VALUES (:index, :site_id, :abb, :name, :elevation, :latitude, :longitude, :network)
    """,
    site,
)

### delete a site

In [70]:
site = db.find_site_info(abb = 'ABC').to_dict()
site

{'index': 10,
 'site_id': 9,
 'abb': 'ABC',
 'name': 'Example Site',
 'elevation': 1520.5,
 'latitude': 39.7392,
 'longitude': -104.9903,
 'network': 'MyNetwork'}

In [74]:
columns = site.keys()

where_clause = " AND ".join(
    f'"{column}" = :{column}'
    for column in columns
)

sql = f"""DELETE FROM sites WHERE {where_clause}"""
# sql = f"""SELECT * FROM sites WHERE {where_clause}"""

In [75]:
db.execute_query(sql, site)

In [ ]:
cursor.execute(sql, site)
conn.commit()

In [76]:
db.find_site_info(abb = 'ABC')

ValueError: No site found with abb ABC

In [ ]:
site_id = 123

cursor.execute(
    """
    DELETE FROM site
    WHERE site_id = ?
    """,
    (site_id,),
)

conn.commit()

In [ ]:
if cursor.rowcount == 0:
    print("No site found with that site_id")
else:
    print(f"Deleted {cursor.rowcount} site row(s)")

# update sites table (this should no longer be necessary)

In [ ]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.surfrad.surfrad as atmsrf

In [ ]:
reload(atmsrf)

In [ ]:
overwrite = True

In [ ]:
df = db.dump_table('sites')
df = df.drop('index', axis=1)
df

In [ ]:
# df = df.sort_values('site_id')

In [ ]:
# create the table
####
for site in atmsrf._locations:
    # print(site)
    abb = site['abbreviation'][0].lower()
    print(abb)
    if (df.abb == abb).sum() > 0:
        if not overwrite:
            print(f'{abb} already in table ... skip')
            continue
        else:
            exists = df[df.abb == abb].iloc[0]
            site_id = exists.site_id
            index = exists.name
            df = df.drop(index)
    else:
        site_id  = df.site_id.max() + 1
        index = df.index.max() + 1
        
    
    row = dict(site_id = site_id,
               abb = abb,
               name = site['name'],
               network = 'surfrad',
               elevation = site['alt'],
               latitude = site['lat'],
               longitude = site['lon'],
              )
    row
         
    
    df = pd.concat([df,pd.DataFrame(row, index=[index])])

    ######
    # below are the cases where there are alternative names

    if row['abb'] == 'bnd':
        # first remove if they exist already
        abbalt = 'bon'
        df.drop(df[df.abb == abbalt].index, inplace = True)
        row['abb'] = abbalt
        df = pd.concat([df,pd.DataFrame(row, index=[index])])
    if row['abb'] == 'fpk':
        # row['abb'] = 'fpe'
        abbalt = 'fpe'
        df.drop(df[df.abb == abbalt].index, inplace = True)
        row['abb'] = abbalt
        df = pd.concat([df,pd.DataFrame(row, index=[index])])

df = df.sort_values('site_id')

In [ ]:
df

In [ ]:
# save into database
#####
if 0:
    with sqlite3.connect(db.path2db) as dbt:
        df.to_sql('sites', dbt, if_exists='replace')

# update MFRSR_History

first download the most up-to-date MFRSR_History file from [here](https://docs.google.com/spreadsheets/d/1pzBw4ZPxWhRVg-wM69hxUEOcbjFAc42nzZ9czwYdl-c/edit?gid=1879435883#gid=1879435883)

In [1]:
import surfradpy.database as srfdb

In [2]:
reload(srfdb)

In [3]:
p2db = 'surfrad_database.db'
db = srfdb.SurfradDatabase(p2db)

In [4]:
out = db.update_mfrsr_history('MFRSR_History.xlsx', 
                              replace=True,
                              # dryrun=True
                             )

Instrument 451 has fist column with the name Purchased SN 451 w/stand from eBay July 2024 not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?
Instrument 607 has fist column with the name Brookhaven MFRSR not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?
Instrument 559 has fist column with the name Thermopile MFRSR (Standard filters) not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?
Instrument 584 has fist column with the name MFRSR purchased around 2013 not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?

In [ ]:
db.

In [ ]:
dft = db.tp_df.iloc[[0]]

In [ ]:
dft.Date_start

In [ ]:
dft.Date_start.dtypes.name == 'datetime64[us]'

In [ ]:
plt = None

In [ ]:
from atmPy.opt_imports import OptionalImport

In [ ]:
mpl = OptionalImport('matplotlib')

In [ ]:
mpl

In [ ]:
plt = OptionalImport('matplotlib.pyplot')

In [ ]:
plt.plot()

In [ ]:
__import__('matplotlib.pyplot')

In [ ]:
import importlib

In [ ]:
plt = importlib.import_module('matplotlib.pyplot')

In [ ]:
plt.plot()