In [3]:
import surfradpy.radflux2netcdf as srfr2nc

In [69]:
reload(srfr2nc)

In [73]:
rfi = srfr2nc.Convert(path2fld_in='/Volumes/aftp/g-rad/surfrad/RadFlux/',    
                          path2fld_out='/Volumes/grad/surfrad/products_level4/radflux/v{version}/',    
                          sites=['tbl'],#, 'dra', 'fpk', 'gwn', 'psu', 'sxf', 'bon'],    
                          start='360 days',    
                          overwrite=False,
                          reporter = False,
                          verbose = True)

starting convert

In [74]:
out = rfi.workplan
out

patterns: ['2025/*.lw1', '2026/*.lw1']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/red
red not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/.ipynb_checkpoints
.ipynb_checkpoints not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/gwn
gwn not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/psu
psu not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/was
was not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/fpk
fpk not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/sxf
sxf not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/.DS_Store
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/rut
rut not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/slv
slv not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/bao
bao not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/eug
eug not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/README_SURFRAD_RadFlux.pdf
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/RadFlux_Uncert_Table.pdf
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/bon
bon not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/tbl

checking: /Volumes/aftp/g-rad/surfrad/RadFlux/README_SURFRAD_RadFlux.txt
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/plv
plv not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/dra
dra not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/ruf
ruf not in ['tbl']
checking: /Volumes/aftp/g-rad/surfrad/RadFlux/cdn
cdn not in ['tbl']

,p2f_in,site,p2f_out
date,,,
2026-01-19,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-01-20,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-01-21,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-01-22,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-01-23,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
...,...,...,...
2026-07-01,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-02,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-03,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-04,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-05,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...

In [72]:
out

,p2f_in,site,p2f_out
date,,,
2026-03-06,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-03-07,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-03-08,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-03-09,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-03-10,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
...,...,...,...
2026-07-01,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-02,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-03,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-04,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...
2026-07-05,/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2026/2...,tbl,/Volumes/grad/surfrad/products_level4/radflux/...

In [53]:
fld = out['fld']

In [59]:
pat = out['patterns'][0]
pat

'2026/*.lwl'

In [55]:
pd.DataFrame(fld.glob(pat), columns=['p2f_in'])

Empty DataFrame
Columns: [p2f_in]
Index: []

In [64]:
l = list(fld.glob('2025/*.lw1'))
l.sort()
l

[PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250101.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250102.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250103.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250104.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250105.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250106.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250107.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250108.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250109.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250110.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250111.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250112.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250113.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250114.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250115.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250116.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250117.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250118.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250119.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250120.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250121.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250122.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250123.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250124.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250125.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250126.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250127.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250128.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250129.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250130.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250131.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250201.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250202.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250203.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250204.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250205.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250206.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250207.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250208.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250209.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250210.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250211.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250212.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250213.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250214.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250215.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250216.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250217.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250218.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250219.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250220.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250221.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250222.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250223.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250224.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250225.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250226.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250227.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250228.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250301.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250302.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250303.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250304.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250305.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250306.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250307.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250308.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250309.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250310.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250311.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250312.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250313.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250314.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250315.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250316.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250317.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250318.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250319.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250320.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250321.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250322.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250323.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250324.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250325.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250326.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250327.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250328.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250329.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250330.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250331.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250401.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250402.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250403.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250404.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250405.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250406.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250407.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250408.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250409.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250410.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250411.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250412.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250413.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250414.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250415.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250416.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250417.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250418.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250419.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250420.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250421.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250422.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250423.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250424.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250425.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250426.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250427.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250428.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250429.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250430.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250501.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250502.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250503.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250504.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250505.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250506.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250507.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250508.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250509.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250510.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250511.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250512.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250513.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250514.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250515.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250516.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250517.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250518.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250519.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250520.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250521.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250522.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250523.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250524.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250525.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250526.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250527.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250528.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250529.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250530.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250531.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250601.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250602.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250603.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250604.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250605.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250606.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250607.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250608.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250609.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250610.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250611.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250612.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250613.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250614.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250615.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250616.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250617.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250618.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250619.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250620.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250621.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250622.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250623.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250624.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250625.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250626.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250627.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250628.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250629.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250630.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250701.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250702.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250703.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250704.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250705.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250706.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250707.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250708.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250709.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250710.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250711.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250712.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250713.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250714.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250715.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250716.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250717.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250718.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250719.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250720.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250721.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250722.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250723.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250724.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250725.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250726.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250727.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250728.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250729.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250730.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250731.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250801.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250802.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250803.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250804.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250805.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250806.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250807.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250808.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250809.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250810.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250811.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250812.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250813.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250814.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250815.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250816.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250817.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250818.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250819.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250820.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250821.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250822.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250823.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250824.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250825.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250826.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250827.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250828.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250829.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250830.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250831.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250901.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250902.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250903.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250904.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250905.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250906.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250907.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250908.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250909.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250910.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250911.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250912.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250913.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250914.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250915.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250916.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250917.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250918.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250919.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250920.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250921.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250922.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250923.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250924.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250925.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250926.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250927.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250928.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250929.lw1'),
 PosixPath('/Volumes/aftp/g-rad/surfrad/RadFlux/tbl/2025/20250930.lw1'),

In [ ]:
list(fld.glob('*'))

In [ ]:
/Users/htelg/prog/SURFRAD/surfradpy/radflux2netcdf.py

In [ ]:
    # run = sfraodinv.AODInversion( version=1.0,
    #                                 channels=[415,500, 670, 870, 1625],
    #                                 sites = ['tbl'],
    #                                 start = '20160101',
    #                                 end = None, #'20230101',
    #                                 p2fldaod='/nfs/grad/surfrad/products_level2/aod_netcdf/v1.0/',
    #                                 p2fldout = '/nfs/grad/surfrad/products_level2/aodinversion/1.0/',
    #                                 ignore_in_cloud  = True,
    #                                 test = False,
    #                                 verbose = False,
    #                                 reporter = reporter)
    # run.workplan = run.workplan.sample(frac = 1)
    
    rfi.workplan = rfi.workplan[::-1]
    print(f'workplan.shape: {rfi.workplan.shape}')
    
    rfi.process(error_handling = 'skip')
    
    reporter.wrapup()
    return reporter